### ISSUE TITLE
Publishing to MELPA

### ISSUE THREAD

**Issue by corpix** [mgxm/ob-svgbob#1]
Hello. I would like to help this package to appear on MELPA recipes repository, so I could install it as any other package for Emacs :)
I could fill a request just [like I did](https://github.com/melpa/melpa/pull/4746) with my own package. What do you think about that?

**Comment by mgxm** [comment]
Hey, @corpix Thank you. This would be great. :)

**Comment by corpix** [comment]
Hooray, [it is on MELPA](https://melpa.org/#/ob-svgbob) now!

**Comment by mgxm** [comment]
:tada: 
Thanks! @corpix
